//Select all columns from Orders Table

SELECT * 
FROM ORDERS;

// From specific table
SELECT *
FROM "TIL_PLAYGROUND"."SQL_COURSE"."ORDERS";

// LIMIT Example
SELECT * 
FROM ORDERS
LIMIT 100;

// SELECT all product Ids 
SELECT 
   PRODUCT_ID
FROM ORDERS;

// Return a unqiue list of products_IDs
SELECT DISTINCT
   PRODUCT_ID
   FROM ORDERS;
   
// Return a unqiue list of PRODUCT NAMES
SELECT DISTINCT
   PRODUCT_NAME
   FROM PRODUCTS;
   
// unique list of product IDs per Ship Mode
SELECT DISTINCT
   PRODUCT_ID,
   SHIP_MODE
FROM ORDERS;

//alias as available shipping
SELECT DISTINCT
   PRODUCT_ID,
   SHIP_MODE as "AVAILABLE_SHIPPING"
FROM ORDERS as "0";


// JOIN ON ALIASES
SELECT
    DISTINCT P.PRODUCT_NAME,
    O.SHIP_MODE
FROM
    ORDERS AS O
    INNER JOIN PRODUCTS AS P ON O.PRODUCT_ID = P.PRODUCT_ID;
    
//LEFT JOIN ON ALIAS
SELECT
    DISTINCT O.ORDER_ID,
    RETURNED
FROM
    ORDERS AS O
    LEFT JOIN RETURNED_ORDERS AS R ON O.ORDER_ID = R.ORDER_ID;
    
//FULL JOIN
SELECT
    CUSTOMER_NAME,
    SALES_PERSON_FULLNAME
FROM
    CUSTOMERS AS C
    FULL JOIN CUSTOMER_SALES_REP AS S ON C.CUSTOMER_ID = S.CUSTOMER_ID;
    
  
// FILTER DATA(where)- orders from Customers in Central Region
SELECT *
FROM ORDERS AS O
INNER JOIN CUSTOMERS AS C
      ON O.CUSTOMER_ID=C.CUSTOMER_ID
  WHERE REGION='Central';

//unique list of states and product in central
SELECT DISTINCT
STATE,
PRODUCT_NAME
FROM ORDERS AS O
JOIN PRODUCTS AS P
     ON P.PRODUCT_ID=O.PRODUCT_ID
JOIN CUSTOMERS AS C
     ON O.CUSTOMER_ID=C.CUSTOMER_ID;

//UNIQUE LIST OF CUSTOMER REGIONS AND CITIES FROM ALL REGIONS EXCEPT CENTRAL
SELECT DISTINCT
REGION,
CITY
FROM CUSTOMERS
WHERE REGION <> 'Central';

//EXAMPLE GREATER AND LESS THAN
SELECT *
FROM ORDERS
WHERE QUANTITY >1 AND PROFIT<0;

// BETWEEN
SELECT *
FROM ORDERS
WHERE ORDER_DATE BETWEEN '2019-01-01' AND '2019-12-31';

//AGGREGATION
//count function
SELECT 
    COUNT(ORDER_ID) AS RECORD_COUNT
FROM ORDERS;
    
//COUNT OF UNIQUE PRODUCTS
SELECT count( DISTINCT PRODUCT_ID) 
FROM PRODUCTS;

//SUM FUNCTION
SELECT 
sum(QUANTITY) AS "TOTAL QUANTITY"
FROM ORDERS;

//CHOOSING LEVEL OF DETAIL - GROUP BY
SELECT 
    PRODUCT_ID,
    SUM(QUANTITY) AS TOTAL_QUANTITY
FROM ORDERS
GROUP BY PRODUCT_ID;

//DISTINCT COUNT OF CUSTOMERS BY STATE AND SALES PERSON
SELECT
STATE,
SALES_PERSON_FULLNAME,
count( DISTINCT C.CUSTOMER_ID) AS TOTAL_CUSTOMERS
FROM CUSTOMERS AS C
INNER JOIN CUSTOMER_SALES_REP AS R
   ON C.CUSTOMER_ID=R.CUSTOMER_ID
GROUP BY STATE,SALES_PERSON_FULLNAME;

//MAX AND AVG
SELECT 
STATE,
max(DISCOUNT),
avg(PROFIT)
FROM ORDERS AS O
INNER JOIN CUSTOMERS AS C
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY STATE;

//HAVING EXAMPLE
SELECT 
ORDER_DATE,
AVG(PROFIT) AS AVG_PROFIT
FROM ORDERS
GROUP BY ORDER_DATE
HAVING AVG(PROFIT) > 500;

//SORTING DATA
SELECT DISTINCT
STATE
FROM CUSTOMERS
ORDER BY STATE DESC;

// ORDER BY AGG EXAMPLE
SELECT 
STATE,
count(DISTINCT CUSTOMER_ID) AS CUSTOMER_COUNT
FROM CUSTOMERS
GROUP BY STATE
ORDER BY CUSTOMER_COUNT DESC;